### ISSUE TITLE
Proposal for recording and replaying sessions.

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-vision-android-teaser#119]
It will be very useful if we can add recording and replaying sessions features in teaser app. We can use these features for developments and debug, what's more, customers can also use teaser app to record the session and send session files to us for debug.

1. For recording, we may add  a setting to config saving the session or not. What do we need save?
    - Videos
    - Routes
    - Locations for every second.

We can save all files of one session in a folder with name like "2018-8-30_14:00" 

2. For replaying, there should be a list for all the recorded sessions, by clicking one item to start replying that session or long clicking to delete it.
The progress bar should be used for replying, so we can jump to the point we'd like to see.
The locations for every second can be used to set location engine.

@yunikkk

**Comment by yunikkk** [comment]
The recording and replaying capabilities are integrated to the current Teaser dev branch for some time. It's still on dev branch though, will arrive to the public Google Play release in 0.13.0
