### ISSUE TITLE
What's the BUILD_CORE_FROM_SOURCE???

### ISSUE THREAD

**Issue by h3clikejava** [mapbox/mapbox-vision-android-teaser#151]
Build ERROR: Cannot get property 'BUILD_CORE_FROM_SOURCE' on extra properties extension as it does not exist

**Comment by korshaknn** [comment]
set BUILD_CORE_FROM_SOURCE=false
in local.properties

**Comment by korshaknn** [comment]
@h3clikejava ^^

**Comment by yunikkk** [comment]
@korshaknn at the same time we should handle missing flag as disabled, will fix that @h3clikejava

**Comment by kiryldz** [comment]
`BUILD_CORE_FROM_SOURCE` is actually not needed at all in latest version.
This issue could be closed.
