### ISSUE TITLE
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.vision:mapbox-android-vision-ar:0.11.0.

### ISSUE THREAD

**Issue by estherooi** [mapbox/mapbox-vision-android-teaser#166]
Hi, I am a student doing my final year project, can anyone provide me step by step guidance in this? thanks a lot!

**Comment by yunikkk** [comment]
Hey @estherooi , were you able to resolve the issue?

**Comment by estherooi** [comment]
@yunikkk hi yes, I was able to resolve the issue now. Thanks

**Comment by narayangour** [comment]
what was the solution ? bcoz i am also facing same.

**Comment by Cocorafa** [comment]
Podrías decir cual fue la solución tengo el mismo problema

**Comment by yunikkk** [comment]
@narayangour @Cocorafa have you added Vision as maven dependencies or downloaded .aar-s directly?

**Comment by narayangour** [comment]
i was following this - https://vision.mapbox.com/install/
here it looks added as maven dependencies. i created a new project in android studio and added snippet from above mention link.

**Comment by kiryldz** [comment]
Hi @narayangour - have you added 
```
maven {
 mapboxMavenUser=mapbox
 mapboxMavenToken=YOUR_SECRET_MAPBOX_TOKEN
}
```
to __global__ `~/.gradle/gradle.properties`?

You could paste your project level `build.gradle` and app level `build.gradle` files as well.

**Comment by kiryldz** [comment]
@narayangour @Cocorafa 
We've also checked some logs and it seems indeed that you try to download libs without valid mapbox token. Please go through [instructions](https://vision.mapbox.com/install/) again (especially `Import Vision into your project with a package manager` section).
Also it is possible that Gradle sometimes faces some errors, e.g. while testing it myself I faced an issue that `mapbox-android-vision-safety-0.11.0.aar` could not get downloaded (while `vision` and `vision-ar` were downloaded OK). However I've tried in a moment (synced with gradle files) and could successfully download it.

**Comment by narayangour** [comment]
error solved by creating new token with vision:download permission and added that token into YOUR_SECRET_MAPBOX_TOKEN variable.

but facing issue while running app in mobile from 

https://github.com/mapbox/mapbox-vision-android/tree/dev/Examples/src/main/java/com/mapbox/vision/examples

...it does not show anything like no arrow, sign. same as on web.

can u help me to run the demo same shown on web. how many file i need to add from above git example's.

**Comment by kiryldz** [comment]
@narayangour glad to hear you made tokens work.
Please open as issue in https://github.com/mapbox/mapbox-vision-android repo and provide more information: at least what example you try to run and what did you expect to see.

**Comment by lucagrana** [comment]
To resolve it you have to create a token able to download vision. 
1) Go to account.mapbox.com
2) Click on create a token
3) Named it and flag VISION:DOWNLOAD in secret scopes
4)Copy your new token in gradle.properties
That's all
