### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-vision-android-teaser#55]
Google won't support `android support libraries` for next APIs(from 29+ that is actually Android 10).
Migration guide: https://developer.android.com/jetpack/androidx/migrate

**Comment by vladzima** [comment]
What is this issue about? Any description?

**Comment by RingerJK** [comment]
@vladzima description was added

**Comment by yunikkk** [comment]
@RingerJK is it already done?

**Comment by RingerJK** [comment]
@yunikkk yes, I've done it. [PR](https://github.com/mapbox/mapbox-vision-android-teaser/pull/64) . It's strange, I linked PR to current issue. Will close it manually.
