### ISSUE TITLE
Device Support problem

### ISSUE THREAD

**Issue by wInGSorCE** [mapbox/mapbox-vision-android-teaser#68]
I installed this app on my HTC One(E8) and open , but it says this device is not supported. As i know HTC One is using Qualcomm MSM8975AC Snapdragon 801 and with Android 6.0, seems to fit Vision SDK 's requirement(Android 6 and higher, with QC Snapdragon 8xx) . 
Thanks .

**Comment by yunikkk** [comment]
Hello, while snapdragon 801 is not officially supported now and is pretty old chip we can test or change that in future. I'll keep this ticket to track this.
Also we'll update the docs with the specific snapdragon versions that are supported.

**Comment by wInGSorCE** [comment]
Ok, thank you for the information.

**Comment by wInGSorCE** [comment]
Sorry, I want to ask about another chip ,snapdragon MSM8953 .Because i saw the SupportedSnapdragonBoards.class file that MSM8952 is supported, and i currently have a MSM8953 device(same architecture as 8952). After testing, app is not working on MSM8953, so i want to know is MSM8953 supported?
Thank you Again.

**Comment by yunikkk** [comment]
So it seems that it's the snapdragon 625 modification, that indeed should be compatible. We'll fix the issue in the next release, thanks for discovery.

**Comment by RingerJK** [comment]
@wInGSorCE support MSM8953 will be added in next SDK release(0.4.0)

**Comment by RingerJK** [comment]
@wInGSorCE We decider to postpone support MSM8953 to the next SDK release(0.5.0)
