### ISSUE TITLE
Source Location Warning in AR mode

### ISSUE THREAD

**Issue by maniac-tech** [mapbox/mapbox-vision-android-teaser#71]
Unable to initiate AR Navigation.

As I select a Destionation on the Map, I get a Warning on the bottom reading "Source location is to be determined yet!"

**Comment by yunikkk** [comment]
Hello,

the error means that your device location is not determined yet, so we can not initiate AR navigation. Can you provide more details on how you configure your device?

**Comment by vladzima** [comment]
Closing for now. Feel free to reopen if needed.
